version: '2'
services:
  supplierstraders-app:
    image: supplierstraders
    environment:
      - _JAVA_OPTIONS=-Xmx512m -Xms256m
      - SPRING_PROFILES_ACTIVE=prod,swagger
      - MANAGEMENT_METRICS_EXPORT_PROMETHEUS_ENABLED=true
      - SPRING_DATASOURCE_URL=jdbc:mysql://supplierstraders-mysql:3306/supplierstraders?useUnicode=true&characterEncoding=utf8&useSSL=false&createDatabaseIfNotExist=true
      - JHIPSTER_SLEEP=30 # gives time for other services to boot before the application
      - SPRING_DATA_JEST_URI=http://supplierstraders-elasticsearch:9200
      - SPRING_ELASTICSEARCH_REST_URIS=http://supplierstraders-elasticsearch:9200
    ports:
      - 8080:8080
  supplierstraders-mysql:
    extends:
      file: mysql.yml
      service: supplierstraders-mysql
  supplierstraders-elasticsearch:
    extends:
      file: elasticsearch.yml
      service: supplierstraders-elasticsearch
